spring.application.name=food-price-predictor-backend

#Database configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/food_price_predictor_db
#spring.datasource.username=postgres
#spring.datasource.password=sciencetechnology
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://dpg-d6mt83v5gffc73bnd56g-a.oregon-postgres.render.com/price_sight_db
spring.datasource.username=price_sight_db_user
spring.datasource.password=doie6k5p9vHmvUIrPuTgOErD1i0xzX3d
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
